### ISSUE TITLE
compatibility issue with Ubuntu 22.04?

### ISSUE THREAD

**Issue by BCArg** [MariaNattestad/SplitThreader#10]
Hi Maria,

I have recently upgrade my Ubuntu, from 18.04 all the way to 22.04 and since then split threader is no longer working.

I have re-installed xampp according to the instructions [here](https://medium.com/@dmitvas/install-xampp-on-ubuntu-22-04-dd8e339d75d8) - `xampp-linux-x64-8.2.12-0`

I have then re-installed split threader following the instructions in this page.

When I try to load a valid vcf as well as a valid 'copycat' file I get the following error message:

![image](https://github.com/MariaNattestad/SplitThreader/assets/20555037/77ae82cd-235d-4ba5-a59b-723654d1e533)

When I upgrade my Ubuntu,as far as I recall, there was an issue with Mysql, and when I open XAMPP, I indeed see something with Mysql:

![image](https://github.com/MariaNattestad/SplitThreader/assets/20555037/f54a9361-7be6-458f-9d1b-1e7cc5570655)

Do you think it can be indeed a mysql issue? Or perhaps something else?

Thanks

**Comment by MariaNattestad** [comment]
I recently installed SplitThreader on a new VM myself to serve splitthreader.com, so I have made some code updates. Part of these are updating to python3 and a fix to logging that was needed on that new system, so definitely pull the latest code from the `master` branch.
There is no MySQL database used in SplitThreader, no databases at all.
It's probably python.
What I suggest for debugging is to look inside the `user_data/<run_id>/run_algorithm_errors.log` which will contain the actual error messages coming out of the pipeline and all the scripts.

**Comment by BCArg** [comment]
indeed it appears to be python. The first error message I got was:
``` 
python3: symbol lookup error: python3: undefined symbol: XML_SetHashSalt
```

I did some research and it appeared to be an issue with `libexpat.so` and `libexpat.so.1`

It looked like lampp was using an older version of these two libs:
```
(base) bhinckel@PE44373-U:/opt/lampp/lib$ ll libexpat.*
-rwxr-xr-x 1 root root    829 Jul 11  2019 libexpat.la*
-rw-r--r-- 1 root root 381116 Jul 11  2019 libexpat.a
-rwxr-xr-x 1 root root 198736 Nov 25 09:15 libexpat.so.1.5.2*
lrwxrwxrwx 1 root root     17 Mär 14 14:10 libexpat.so.1 -> libexpat.so.1.5.2*
lrwxrwxrwx 1 root root     17 Mär 14 14:10 libexpat.so -> libexpat.so.1.5.2*
```

whereas on my system I have:
```
(base) bhinckel@PE44373-U:/lib/x86_64-linux-gnu$ ll libexpat.so*
-rw-r--r-- 1 root root 194872 Mär 13 14:28 libexpat.so.1.8.7
lrwxrwxrwx 1 root root     17 Mär 13 14:28 libexpat.so.1 -> libexpat.so.1.8.7
lrwxrwxrwx 1 root root     39 Mär 13 14:28 libexpat.so -> /lib/x86_64-linux-gnu/libexpat.so.1.8.7
```

I have changed the links as following:
```
root@PE44373-U:/opt/lampp/lib# ll libexpat.so*
lrwxrwxrwx 1 root root     39 Mär 19 14:44 libexpat.so -> /lib/x86_64-linux-gnu/libexpat.so.1.8.7
lrwxrwxrwx 1 root root     17 Mär 19 14:47 libexpat.so.1 -> libexpat.so.1.8.7
-rw-r--r-- 1 root root 194872 Mär 19 14:47 libexpat.so.1.8.7
```

and now I get the following error message:
```
Traceback (most recent call last):
  File "/opt/lampp/htdocs/splitthreader/./bin/standardize_variants.py", line 599, in <module>
    main()
  File "/opt/lampp/htdocs/splitthreader/./bin/standardize_variants.py", line 596, in main
    args.func(args)
  File "/opt/lampp/htdocs/splitthreader/./bin/standardize_variants.py", line 50, in run
    if "chrom1,start1,stop1,chrom2,start2,stop2,variant_name" in header:
TypeError: a bytes-like object is required, not 'str'
```

I have installed `xampp-linux-x64-8.2.12-0-installer.run`, which, I assume, will install specific versions of `libexpat.so` and `libexpat.so.1`.

So I guess it is an incompatibility between xampp, splitthreader and `libexpat.so` and `libexpat.so.1` on my system? Which versions I should aim for?

As for the split threader installation, I have just did `git clone https://github.com/marianattestad/splitthreader`, so I assume I pulled the latest version from master branch

**Comment by MariaNattestad** [comment]
I don't really know how to help debug this, unfortunately. I don't generally recommend trying to install SplitThreader yourself locally, since I built it back when I was less good at packaging software to make it easy to install. Sorry about that! Are you able to use it at splitthreader.com instead?

**Comment by BCArg** [comment]
I can use the online version yes, we avoid loading patients' data into any web server though.
Thanks for checking in any case

**Comment by MariaNattestad** [comment]
I had considered making an update to SplitThreader that will make it easier to use but take a lot of time investment on my part, but I don't know that there's enough demand for SplitThreader at this point, and I have some other projects with many more users like [Ribbon](https://genomeribbon.com). If you can help me understand your use case and what kind of data you have though, I might be able to incorporate those needs into my other visualization projects like Ribbon that is very lightweight and easy to install locally. If you're interested to talk, please email me at maria.nattestad@gmail.com. Thanks!
