### ISSUE TITLE
About files upload problem

### ISSUE THREAD

**Issue by shunhuahan** [MariaNattestad/SplitThreader#2]
I followed the Local deployment method in a mac. It worked and showed me result for the first time, but since the second time the page just shows me "No files uploaded" after I chose the files and clicked submit, like following:
![image](https://cloud.githubusercontent.com/assets/22645701/20893037/52b337fa-bade-11e6-933f-e091dc08e3a6.png)
I tried re-download SplitThreader under htdocs folder but didn't work. So I need some help in troubleshooting, thanks!

**Comment by MariaNattestad** [comment]
It is a permissions issue for creating new files in the folders user_data and user_uploads. If you go into the splitthreader directory and type chmod 777 user_data and then chmod 777 user_uploads, that should do it. I'll add a note about this to the directions. Thanks!

**Comment by shunhuahan** [comment]
Thanks for the reply, now I could successfully submit the files but another error came as followed:
![image](https://cloud.githubusercontent.com/assets/22645701/20938870/afc7fea8-bbba-11e6-9a13-cf0a9ddc28ba.png)
The uploaded files are in the right format, I tried that on `http://splitthreader.com/` and they seem to be working.

**Comment by MariaNattestad** [comment]
It may have something to do with your R installation since CN segmentation relies on R but the parsing the input files only uses Python. You can see the error messages by going into the user_data directory, into the folder for your most recent run, and looking at the run_algorithm_errors.log file which contains all the errors encountered by SplitThreader while parsing your data and running the copy number segmentation.

**Comment by shunhuahan** [comment]
Thanks! I solved the issue by checking error log, it turned out I need to create python virtual environment and install R package "DNAcopy" to get it work, here is the whole installation command for me:
```
cd /Applications/XAMPP/htdocs/
git clone https://github.com/marianattestad/splitthreader
chmod 777 user_uploads
chmod 777 user_data
virtualenv python_env
source ./python_env/bin/activate
R
source("https://bioconductor.org/biocLite.R")
biocLite("DNAcopy")
q()
```
