### ISSUE TITLE
No output in SplitThreader

### ISSUE THREAD

**Issue by Mmark94** [MariaNattestad/SplitThreader#3]
Hi, I am trying to use SplitThreader on my yeast genome data, but I have some problems. I upload the .bedpe file (from Sniffles) and the .csv file (from copycat), but I can't see any output, I can't see the structural variations or the coverage plot.

The first message seems ok:
"Starting...
1. Reading input files

Sniffles bedpe file

Number of variants filtered out due to small size (minimum size is 1000): 48

2. Segmenting copy number

done"

but I don't see nothing:
![output](https://user-images.githubusercontent.com/34945781/40188139-27c3a5f8-59f1-11e8-9c9f-5a7f7f06fe01.PNG)

It's also strange for me the fact that when I try to use copycat I receive this warning:
 /home/cai/copycat-master/copycat ALL-MMy005_ngmlr_sort.bam -g chr.txt MMy005-copycat
"
*****
*****WARNING: Genome (-g) files are ignored when BAM input is provided. 
*****
"
When the usage example tells that the genome file is needed:
Usage:
copycat alignments.sorted.bam genome_file output_prefix 

Can this be related with the fact that I have not output in SplitThreader?

Thanks

**Comment by MariaNattestad** [comment]
The warning is likely coming from bedtools, which copycat uses under the hood, so you may have a newer version installed that doesn't need the -g file anymore. The coverage csv file is human-readable so you can check if it makes sense and has the same chromosome names as your variant file. If you post the first few lines of that coverage file, I can help you troubleshoot.

**Comment by Mmark94** [comment]
Thanks, these are the first few lines of my .csv file:

chromosome,start,end,unsegmented_coverage
chr01,0,10000,8.1822
chr01,10000,20000,9.213
chr01,20000,30000,10.2026
chr01,30000,40000,11.8462
chr01,40000,50000,11.983
chr01,50000,60000,15.3404
chr01,60000,70000,13.9089
chr01,70000,80000,16.1405
chr01,80000,90000,17.0873
chr01,90000,100000,17.6456
chr01,100000,110000,22.039
chr01,110000,120000,19.9698
chr01,120000,130000,14.9096
chr01,130000,140000,17.0698
chr01,140000,150000,17.4384
chr01,150000,160000,17.5956
chr01,160000,170000,27.1267
chr01,170000,180000,23.1103
chr01,180000,190000,18.0006
chr01,190000,200000,14.8789
chr01,200000,210000,9.5362
chr01,210000,220000,10.512
chr01,220000,230000,9.9087
chr01,230000,230222,3.24324
chr02,0,10000,5.3064
chr02,10000,20000,6.3053
chr02,20000,30000,6.5715
chr02,30000,40000,11.7827
chr02,40000,50000,11.4552
chr02,50000,60000,13.1165
chr02,60000,70000,14.2613
chr02,70000,80000,15.047
chr02,80000,90000,15.8066
chr02,90000,100000,15.5467
chr02,100000,110000,17.6214

Seems to me that the chromosome names are correct for the yeast, ranging from 1 to 16.
Is there any limit to the chromosomes size? I am most interested in one of these chromosomes that is only 100kb long, its name is chrsyn09R in my sample, but I didn't see it in the graphic circle and neither the mtDNA (85kb).

**Comment by MariaNattestad** [comment]
SplitThreader was made to work for cancer data, so it was assumed to be human data, and it filters automatically to the main chromosomes. It might take some work to make it work for yeast, but if you send me the URL I can take a look. In the meantime, you might find my other tool Ribbon at genomeribbon.com to be useful. Ribbon isn't specific to human and it also shows the variants as connections between chromosomes.

**Comment by Mmark94** [comment]
Thanks a lot, this is the URL for my SplitThreader data:
http://splitthreader.com/analysis.php?code=SPDiHhRGe1WdKTyTUErG

I already know Ribbon, is a very useful tool and it has a very cool design, I used it many times, but now I have some strains with one circular chromosome with a very complex structure and I wasn't able to solve/understand them also with Ribbon

URL of Ribbon data for example:
http://genomeribbon.com/?perma=Nc78rfW0fb

So I wanted to try using this other tool and see if the things are going better.
