### ISSUE TITLE
add new genome

### ISSUE THREAD

**Issue by malaria123** [MariaNattestad/SplitThreader#5]
Hi Maria,
Thank you for the wonderful tool. I have just started playing around with SplitThreader. I am wondering if it is possible to upload other genome as annotation since I study malaria parasites. 
Thanks again,
Xu

**Comment by MariaNattestad** [comment]
You have long-range SVs in the malaria genome? Interesting!

It should be pretty easy to register a new reference genome annotation by forking this repo and then:

1. Adding your annotation file to resources/annotation.
2. Adding to the code here:
https://github.com/MariaNattestad/SplitThreader/blob/ac42d37856fcbaf38095b7f10b22c31863786d76/js/SplitThreader_visualizer.js#L37
3. Of course then you have to launch SplitThreader locally. I believe the README has instructions for that.

So it's not as easy as using splitthreader.com directly, but still totally possible.

**Comment by malaria123** [comment]
yes, we do detect long -range SVs in Plasmodium falciparum, can i ask why are you surprised? i thought it was a common genomic trait for all of the organisms.
I managed to operate split threader locally, however i keep having an error:

Starting...
1. Reading input files

Error: No standardized variant file created

fail

would you please let me know how to fix it.

Thanks,
Xu

**Comment by MariaNattestad** [comment]
I'm not that surprised, just interested. I've mostly worked with human genomes, and humans have a lot less variation between individuals, so having enough long-range SVs to make SplitThreader useful (i.e. more than 1) is pretty rare except in cancer.

Searching for the error in this repo you can see it's in the web_pipeline script, so try seeing if you can find the error and debug it from there. You can always run the web_pipeline script from the command-line if you can't view the errors when running it from a web browser, and then it's just a matter of debugging it from there.

**Comment by malaria123** [comment]
yes, actually it happens more often in the parasites than I would think. I found splitthreader is perfect for me to display and visualize my data, and it is so easy for me to use (at least at the beginning). I am also trying to use Ribbon. Being a biologist don't know much bioinformatics, I'm really counting on tools like splitthreader and Ribbon. So thank you!
I also wrote you email but I guess you stopped using cold spring harbor email. 
Actually the major reason that I am trying to use splitthreader locally, because i had trouble with uploading files with the online version yesterday, but today it is working again, I am not sure if it is normal. 

So I looked at the the script:

Last login: Thu Apr 22 09:43:30 on ttys000
/Users/lak9015a/.bitnami/stackman/machines/xampp/volumes/root/htdocs/splitthreader/bin/web_pipeline ; exit;

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
(base) MAC184761:~ lak9015a$ /Users/lak9015a/.bitnami/stackman/machines/xampp/volumes/root/htdocs/splitthreader/bin/web_pipeline ; exit;
ERROR in SplitThreader: No variants file given
Usage:
web_pipeline variants copynumber output_prefix
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

Thank you!

Xu

**Comment by MariaNattestad** [comment]
Okay, so it might be too much for you to try to debug this if you don't really have much coding experience, and I can't really help you with it remotely, it would just be too time-consuming. You should be able to use the visualization in SplitThreader without the annotation files, and otherwise Ribbon is easier because you can load your own annotation files through the UI there.
Sorry I can't be more help with this!

**Comment by malaria123** [comment]
Don't be sorry. I don't have to use it locally. I am actually using it online and it is totally fine for the most time. I sometimes have the similar issue as "No output in SplitThreader #3", but not always, I wonder why, I know there are SVs in the sample and my input were always generated the same way. I am wondering why it works for some samples but not others. Thanks!
