### ISSUE TITLE
ERROR: header must include chromosome  Error: No standardized copy number file created

### ISSUE THREAD

**Issue by Deeptirao** [MariaNattestad/SplitThreader#7]
Hi, I tried running splitthreader on my plant genome files and got the following error message:
Starting...

1. Reading input files

NOTE: Contains 'VCF' in a header row (starting with #), so treating it like a VCF file.

VCF file

WARNING: No strand info for records. Variants will be ignored by visualizer:

Chr1 1949005 Sniffles2.INV.469S0 N 60 PASS PRECISE;SVTYPE=INV;SVLEN=3040;END=1952045;SUPPORT=4;COVERAGE=7,7,10,0,5;STRAND=+;AF=0.500;STDEV_LEN=0.000;STDEV_POS=0.000 GT:GQ:DR:DV 0/1:28:4:4

Chr1 1964048 Sniffles2.INV.46AS0 N 60 PASS PRECISE;SVTYPE=INV;SVLEN=58836;END=2022884;SUPPORT=4;COVERAGE=9,5,9,8,8;STRAND=-;AF=0.400;STDEV_LEN=0.000;STDEV_POS=0.000 GT:GQ:DR:DV 0/1:23:6:4

Chr1 1964369 Sniffles2.INV.46BS0 N 60 PASS PRECISE;SVTYPE=INV;SVLEN=58026;END=2022395;SUPPORT=4;COVERAGE=5,5,9,8,8;STRAND=+;AF=0.500;STDEV_LEN=0.000;STDEV_POS=0.000 GT:GQ:DR:DV 0/1:28:4:4

Chr1 3007635 Sniffles2.INV.473S0 N 58 PASS PRECISE;SVTYPE=INV;SVLEN=31029551;END=34037186;SUPPORT=6;COVERAGE=14,8,14,0,7;STRAND=+;AF=0.462;STDEV_LEN=0.000;STDEV_POS=0.000 GT:GQ:DR:DV 0/1:40:7:6

Chr1 3012350 Sniffles2.INV.474S0 N 58 PASS PRECISE;SVTYPE=INV;SVLEN=31024841;END=34037191;SUPPORT=7;COVERAGE=24,8,10,0,7;STRAND=-;AF=0.350;STDEV_LEN=0.000;STDEV_POS=0.000 GT:GQ:DR:DV 0/1:33:13:7

Total variants affected: 361 out of 8239 total variants

You can specify strands among the other tags in the vcf file's info field, for example: STRANDS=+-:5; where 5 is the number of split reads

Visualizer will ignore these variants where it could not guess the strands from the variant types

All variant types: DUP, INV, BND, DEL, INS

Number of variants filtered out due to small size (minimum size is 1000): 2016

NOTE: Found not enough comma-separated column names in header: treating file as whitespace delimited instead

ERROR: header must include chromosome

Error: No standardized copy number file created

fail 

**My vcf header looks like this-**
##fileformat=VCFv4.2
##source=Sniffles2_2.2
##command="/home/deepti/anaconda3/bin/sniffles --input pacbio.vs.nip.paf.sorted.bam --vcf pacbio.vs.nip.paf.sorted.bam.minsupport3.minsvlen1000.mapq30.vcf --minsupport 3 --minsvlen 1000 --mapq 30"
##fileDate="2023/08/28 20:02:26"
##contig=<ID=Chr1,length=43270923>
##contig=<ID=Chr2,length=35937250>
##contig=<ID=Chr3,length=36413819>
##contig=<ID=Chr4,length=35502694>
##contig=<ID=Chr5,length=29958434>
##contig=<ID=Chr6,length=31248787>
##contig=<ID=Chr7,length=29697621>
##contig=<ID=Chr8,length=28443022>
##contig=<ID=Chr9,length=23012720>
##contig=<ID=Chr10,length=23207287>
##contig=<ID=Chr11,length=29021106>
##contig=<ID=Chr12,length=27531856>
##contig=<ID=ChrM,length=490520>
##contig=<ID=ChrC,length=134525>
##ALT=<ID=INS,Description="Insertion">
##ALT=<ID=DEL,Description="Deletion">
##ALT=<ID=DUP,Description="Duplication">
##ALT=<ID=INV,Description="Inversion">
##ALT=<ID=BND,Description="Breakend; Translocation">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype quality">
##FORMAT=<ID=DR,Number=1,Type=Integer,Description="Number of reference reads">
##FORMAT=<ID=DV,Number=1,Type=Integer,Description="Number of variant reads">
##FORMAT=<ID=ID,Number=1,Type=String,Description="Individual sample SV ID for multi-sample output">
##FILTER=<ID=PASS,Description="All filters passed">
##FILTER=<ID=GT,Description="Genotype filter">
##FILTER=<ID=SUPPORT_MIN,Description="Minimum read support filter">
##FILTER=<ID=STDEV_POS,Description="SV Breakpoint standard deviation filter">
##FILTER=<ID=STDEV_LEN,Description="SV length standard deviation filter">
##FILTER=<ID=COV_MIN,Description="Minimum coverage filter">
##FILTER=<ID=COV_CHANGE,Description="Coverage change filter">
##FILTER=<ID=COV_CHANGE_FRAC,Description="Coverage fractional change filter">
##FILTER=<ID=MOSAIC_AF,Description="Mosaic maximum allele frequency filter">
##FILTER=<ID=ALN_NM,Description="Length adjusted mismatch filter">
##FILTER=<ID=STRAND,Description="Strand support filter">
##FILTER=<ID=SVLEN_MIN,Description="SV length filter">
##INFO=<ID=PRECISE,Number=0,Type=Flag,Description="Structural variation with precise breakpoints">
##INFO=<ID=IMPRECISE,Number=0,Type=Flag,Description="Structural variation with imprecise breakpoints">
##INFO=<ID=MOSAIC,Number=0,Type=Flag,Description="Structural variation classified as putative mosaic">
##INFO=<ID=SVLEN,Number=1,Type=Integer,Description="Length of structural variation">
##INFO=<ID=SVTYPE,Number=1,Type=String,Description="Type of structural variation">
##INFO=<ID=CHR2,Number=1,Type=String,Description="Mate chromsome for BND SVs">
##INFO=<ID=SUPPORT,Number=1,Type=Integer,Description="Number of reads supporting the structural variation">
##INFO=<ID=SUPPORT_INLINE,Number=1,Type=Integer,Description="Number of reads supporting an INS/DEL SV (non-split events only)">
##INFO=<ID=SUPPORT_LONG,Number=1,Type=Integer,Description="Number of soft-clipped reads putatively supporting the long insertion SV">
##INFO=<ID=END,Number=1,Type=Integer,Description="End position of structural variation">
##INFO=<ID=STDEV_POS,Number=1,Type=Float,Description="Standard deviation of structural variation start position">
##INFO=<ID=STDEV_LEN,Number=1,Type=Float,Description="Standard deviation of structural variation length">
##INFO=<ID=COVERAGE,Number=.,Type=Float,Description="Coverages near upstream, start, center, end, downstream of structural variation">
##INFO=<ID=STRAND,Number=1,Type=String,Description="Strands of supporting reads for structural variant">
##INFO=<ID=AC,Number=.,Type=Integer,Description="Allele count, summed up over all samples">
##INFO=<ID=SUPP_VEC,Number=1,Type=String,Description="List of read support for all samples">
##INFO=<ID=CONSENSUS_SUPPORT,Number=1,Type=Integer,Description="Number of reads that support the generated insertion (INS) consensus sequence">
##INFO=<ID=RNAMES,Number=.,Type=String,Description="Names of supporting reads (if enabled with --output-rnames)">
##INFO=<ID=AF,Number=1,Type=Float,Description="Allele Frequency">
##INFO=<ID=NM,Number=.,Type=Float,Description="Mean number of query alignment length adjusted mismatches of supporting reads">
##INFO=<ID=PHASE,Number=.,Type=String,Description="Phasing information derived from supporting reads, represented as list of: HAPLOTYPE,PHASESET,HAPLOTYPE_SUPPORT,PHASESET_SUPPORT,HAPLOTYPE_FILTER,PHASESET_FILTER">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  SAMPLE

**The copycat file attached:**
head *seg
Coverage	Chr1	0	10000	9.1903
Coverage	Chr1	10000	20000	8.5728
Coverage	Chr1	20000	30000	6.2993
Coverage	Chr1	30000	40000	4.1048
Coverage	Chr1	40000	50000	16.7272
Coverage	Chr1	50000	60000	27.4103
Coverage	Chr1	60000	70000	9.5294
Coverage	Chr1	70000	80000	9.7014
Coverage	Chr1	80000	90000	12.1733
Coverage	Chr1	90000	100000	9.9803

**I have also tried bedpe as input instead of vcf. It gives the following message:**
Starting...

1. Reading input files

ERROR: Columns 9 and 10 must only contain + or -

Error: No standardized variant file created

fail 

**The bedpe file:**
head pacbio.vs.nip.paf.sorted.bam.minsupport3.minsvlen1000.mapq30.bedpe
#CHROM_A	START_A	END_A	CHROM_B	START_B	END_B	ID	QUAL	STRAND_A	STRAND_B	TYPE	FILTER	INFO	FORMAT	SAMPLE
Chr1	100144	100145	Chr1	103713	103714	Sniffles2.DEL.157S0	60	.	.	DEL	PASS	PRECISE;SVTYPE=DEL;SVLEN=-3569;END=103714;SUPPORT=5;COVERAGE=8,4,4,4,5;STRAND=+-;AF=1.000;STDEV_LEN=0.000;STDEV_POS=0.000	GT:GQ:DR:DV	1/1:13:0:5
Chr1	284163	284164	Chr1	288006	288007	Sniffles2.DEL.159S0	60	.	.	DEL	GT	PRECISE;SVTYPE=DEL;SVLEN=-3843;END=288007;SUPPORT=3;COVERAGE=15,0,18,0,0;STRAND=+-;AF=0.167;STDEV_LEN=0.000;STDEV_POS=0.000	GT:GQ:DR:DV	0/0:11:15:3
Chr1	313271	313272	Chr1	314322	314323	Sniffles2.DEL.15AS0	60	.	.	DEL	PASS	PRECISE;SVTYPE=DEL;SVLEN=-1051;END=314323;SUPPORT=9;COVERAGE=8,8,8,8,11;STRAND=+-;AF=1.000;STDEV_LEN=0.000;STDEV_POS=0.000	GT:GQ:DR:DV	1/1:25:0:9
Chr1	319626	319627	Chr1	319626	319627	Sniffles2.INS.0S0	60	.	.	INS	PASS	PRECISE;SVTYPE=INS;SVLEN=2208;END=319627;SUPPORT=6;COVERAGE=10,6,6,6,7;STRAND=+-;AF=1.000;STDEV_LEN=1.155;STDEV_POS=0.000;SUPPORT_LONG=0	GT:GQ:DR:DV	1/1:16:0:6
Chr1	398133	398134	Chr1	399137	399138	Sniffles2.DEL.15BS0	60	.	.	DEL	PASS	IMPRECISE;SVTYPE=DEL;SVLEN=-1004;END=399138;SUPPORT=7;COVERAGE=0,1,1,1,8;STRAND=+-;AF=1.000;STDEV_LEN=389.157;STDEV_POS=0.000	GT:GQ:DR:DV	1/1:19:0:7
Chr1	432165	432166	Chr1	433616	433617	Sniffles2.DEL.15DS0	60	.	.	DEL	PASS	PRECISE;SVTYPE=DEL;SVLEN=-1451;END=433617;SUPPORT=10;COVERAGE=10,9,9,9,9;STRAND=+-;AF=1.000;STDEV_LEN=0.000;STDEV_POS=0.000	GT:GQ:DR:DV	1/1:27:0:10
Chr1	459898	459899	Chr1	459898	459899	Sniffles2.INS.2S0	60	.	.	INS	PASS	PRECISE;SVTYPE=INS;SVLEN=3901;END=459899;SUPPORT=5;COVERAGE=8,5,5,5,9;STRAND=+-;AF=1.000;STDEV_LEN=2.309;STDEV_POS=0.000;SUPPORT_LONG=0	GT:GQ:DR:DV	1/1:30:0:11
Chr1	609649	609650	Chr1	609649	609650	Sniffles2.INS.3S0	60	.	.	INS	PASS	PRECISE;SVTYPE=INS;SVLEN=3546;END=609650;SUPPORT=3;COVERAGE=14,3,3,3,9;STRAND=+-;AF=1.000;STDEV_LEN=2.646;STDEV_POS=0.000;SUPPORT_LONG=0	GT:GQ:DR:DV	1/1:16:0:6
Chr1	620858	620859	Chr4	3727678	3727679	Sniffles2.BND.4E5S0	60	.	.	BND	PASS	PRECISE;SVTYPE=BND;SUPPORT=6;COVERAGE=0,0,14,11,11;STRAND=+-;AF=0.500;CHR2=Chr4;STDEV_POS=0.000	GT:GQ:DR:DV	0/1:43:6:6

Please suggest accordingly

**Comment by MariaNattestad** [comment]
I think this is an issue with the copy number input, not the VCF. How did you generate the copy number input file?

**Comment by Deeptirao** [comment]
I used copycat to generate it.

**Comment by MariaNattestad** [comment]
Maybe something got outdated about my old copycat script's dependencies or something? The format expected is this (from http://splitthreader.com/example_copycat.txt):

```
chromosome,start,end,unsegmented_coverage
1,0,10000,0.0126
1,10000,20000,73.2209
1,20000,30000,46.4863
1,30000,40000,13.6247
```

so the main thing yours is missing is that header row.

@vmukhina said they used "mosdepth" in #6 to generate the copy number file for SplitThreader, which was faster than the little copycat script I threw together using bedtools back in the day. You can also use what you already have, just add a header like  above with `chromosome,start,end,unsegmented_coverage` (change to tab separated if that's what your file is).
